export default {
  title: { en: "📞 Get In Touch", es: "📞 Ponte en Contacto", fr: "📞 Contactez-moi" },
  description: {
    en: "Ready to bring your ideas to life? Let's discuss your project and explore how we can work together.",
    es: "¿Listo para dar vida a tus ideas? Hablemos de tu proyecto y exploremos cómo podemos trabajar juntos.",
    fr: "Prêt à donner vie à vos idées ? Discutons de votre projet et explorons comment nous pouvons travailler ensemble.",
  },
  contactInfo: { en: "Contact Info", es: "Información de Contacto", fr: "Coordonnées" },
  sendMessage: { en: "Send Message", es: "Enviar Mensaje", fr: "Envoyer un Message" },
  addressLabel: { en: "Address", es: "Dirección", fr: "Adresse" },
  addressValue: { en: "Cairo, Egypt", es: "El Cairo, Egipto", fr: "Le Caire, Égypte" },
  phoneLabel: { en: "Phone", es: "Teléfono", fr: "Téléphone" },
  emailLabel: { en: "Email", es: "Correo Electrónico", fr: "E-mail" },
  whatsappChat: { en: "Chat on WhatsApp", es: "Chatear por WhatsApp", fr: "Discuter sur WhatsApp" },
  letsWork: { en: "Let's work together!", es: "¡Trabajemos juntos!", fr: "Travaillons ensemble !" },
  formDescription: {
    en: "Fill out the form below and I'll get back to you as soon as possible.",
    es: "Complete el formulario a continuación y le responderé lo antes posible.",
    fr: "Remplissez le formulaire ci-dessous et je vous répondrai dès que possible.",
  },
  nameLabel: { en: "Name", es: "Nombre", fr: "Nom" },
  namePlaceholder: { en: "Your Name", es: "Tu Nombre", fr: "Votre Nom" },
  emailFieldLabel: { en: "Email", es: "Correo Electrónico", fr: "E-mail" },
  emailPlaceholder: { en: "Your Email", es: "Tu Correo", fr: "Votre E-mail" },
  subjectLabel: { en: "Subject", es: "Asunto", fr: "Sujet" },
  subjectPlaceholder: { en: "Subject", es: "Asunto", fr: "Sujet" },
  messageLabel: { en: "Message", es: "Mensaje", fr: "Message" },
  messagePlaceholder: { en: "Your Message", es: "Tu Mensaje", fr: "Votre Message" },
  sendButton: { en: "Send Message", es: "Enviar Mensaje", fr: "Envoyer le Message" },
  characters: { en: "characters", es: "caracteres", fr: "caractères" },
};
